# Generated by Django 3.1.7 on 2021-03-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
                ('booktitle', models.CharField(max_length=120)),
                ('bookauth', models.CharField(max_length=120)),
                ('bookaval', models.BooleanField()),
            ],
        ),
    ]
