# Generated by Django 3.1.7 on 2021-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='bookaval',
            field=models.CharField(max_length=120),
        ),
    ]
