# Generated by Django 3.1.5 on 2021-03-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210316_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='bookauth',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='bookaval',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='booktitle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
